version: "3.3"

services:
  my-frontend-app:
    container_name: my-frontend-app
    image: my-frontend-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:80"
    restart: "always"